### ISSUE TITLE
Active Task name is not updated with task renaming

### ISSUE THREAD

**Issue by ischlag** [mank319/Go-For-It#88]
Active Task name in the _Timer_ tab is not updated if a task in the _To-Do_ tab is renamed. It is only updated if I switch focus to another task and back or by going to settings -> refresh -> and reselect the task.

Reproduce like this: 

1. remove all tasks from your _To-Do_ tab
2. create a new task _testA1_
3. select newly created task by clicking on it in the _To-Do_ tab
4. switch to the _Timer_ tab to see _Active Task: testA1_
5. go back to the _To-Do_ tab
6. click on the _testA1_ label and rename it to _testA2_ and press enter
7. switch to the to-do tab and see _Active Task: testA1_ (this should now be testA2 in my opinion)

**Comment by mank319** [comment]
Thanks @ischlag for reporting this. We already recognised this behaviour and it is already fixed in @JMoerman's `wip` branch which will be merged in at some point in the future.
I will however leave this issue open until then :wink:

**Comment by JMoerman** [comment]
This should be fixed now, but I just got a segfault I have yet to reproduce. It may take a bit of time for this to land.

**Comment by JMoerman** [comment]
I see that the ppa hasn't been updated in a while, so this issue still happens with Ubuntu builds.

**Comment by mank319** [comment]
@JMoerman, @ischlag the PPA has been updated and the launchpad builds were successful :wink:
